export const PERMISSIONS = {
  EMPENOS: {
    CREAR: "READ_CHATS",
    CONSULTAR_LISTADO: "READ_CHATS",
    CONSULTAR_DETALLADO: "READ_CHATS",
    REGISTRAR_INTERESES: "READ_CHATS",
    RETIRAR: "READ_CHATS",
  },
  USUARIOS: {
    CONSULTAR: "READ_CHATS",
    CREAR: "READ_CHATS",
  },
  CLIENTES: {
    CONSULTAR: "READ_CHATS",
    CREAR: "READ_CHATS",
    ACTUALIZAR: "READ_CHATS",
  },
} as const;
